# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

"""
python wrapping of EXOoffline software
"""

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_PyEXOAnalysis', [dirname(__file__)])
        except ImportError:
            import _PyEXOAnalysis
            return _PyEXOAnalysis
        if fp is not None:
            try:
                _mod = imp.load_module('_PyEXOAnalysis', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _PyEXOAnalysis = swig_import_helper()
    del swig_import_helper
else:
    import _PyEXOAnalysis
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


try:
    import weakref
    weakref_proxy = weakref.proxy
except:
    weakref_proxy = lambda x: x


MAXMODULES = _PyEXOAnalysis.MAXMODULES
class EXOAnalysisManager(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, EXOAnalysisManager, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, EXOAnalysisManager, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _PyEXOAnalysis.new_EXOAnalysisManager(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PyEXOAnalysis.delete_EXOAnalysisManager
    __del__ = lambda self : None;
    def RunAnalysis(self): return _PyEXOAnalysis.EXOAnalysisManager_RunAnalysis(self)
    def FinishAnalysis(self): return _PyEXOAnalysis.EXOAnalysisManager_FinishAnalysis(self)
    def RunEventDisplay(self): return _PyEXOAnalysis.EXOAnalysisManager_RunEventDisplay(self)
    def RegisterModule(self, *args): return _PyEXOAnalysis.EXOAnalysisManager_RegisterModule(self, *args)
    def OrderModules(self): return _PyEXOAnalysis.EXOAnalysisManager_OrderModules(self)
    def GetModulePointer(self, *args): return _PyEXOAnalysis.EXOAnalysisManager_GetModulePointer(self, *args)
    def GetFilterStatus(self, *args): return _PyEXOAnalysis.EXOAnalysisManager_GetFilterStatus(self, *args)
    def GetInputModule(self): return _PyEXOAnalysis.EXOAnalysisManager_GetInputModule(self)
    def GetTalkToManager(self): return _PyEXOAnalysis.EXOAnalysisManager_GetTalkToManager(self)
    def GetErrorLogger(self): return _PyEXOAnalysis.EXOAnalysisManager_GetErrorLogger(self)
    def GetEventData(self): return _PyEXOAnalysis.EXOAnalysisManager_GetEventData(self)
    def GetChannelMap(self): return _PyEXOAnalysis.EXOAnalysisManager_GetChannelMap(self)
    def GetCalibManager(self): return _PyEXOAnalysis.EXOAnalysisManager_GetCalibManager(self)
    def ShowRegisteredModules(self): return _PyEXOAnalysis.EXOAnalysisManager_ShowRegisteredModules(self)
    def ShutDown(self): return _PyEXOAnalysis.EXOAnalysisManager_ShutDown(self)
    def CallTalkTos(self): return _PyEXOAnalysis.EXOAnalysisManager_CallTalkTos(self)
    def translate_nickname(self, *args): return _PyEXOAnalysis.EXOAnalysisManager_translate_nickname(self, *args)
    def print_statistics(self): return _PyEXOAnalysis.EXOAnalysisManager_print_statistics(self)
    def set_verbose(self, *args): return _PyEXOAnalysis.EXOAnalysisManager_set_verbose(self, *args)
EXOAnalysisManager_swigregister = _PyEXOAnalysis.EXOAnalysisManager_swigregister
EXOAnalysisManager_swigregister(EXOAnalysisManager)

MAXMODULENAME = _PyEXOAnalysis.MAXMODULENAME
class EXOAnalysisModule(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, EXOAnalysisModule, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, EXOAnalysisModule, name)
    __repr__ = _swig_repr
    __swig_setmethods__["name"] = _PyEXOAnalysis.EXOAnalysisModule_name_set
    __swig_getmethods__["name"] = _PyEXOAnalysis.EXOAnalysisModule_name_get
    if _newclass:name = _swig_property(_PyEXOAnalysis.EXOAnalysisModule_name_get, _PyEXOAnalysis.EXOAnalysisModule_name_set)
    __swig_setmethods__["analysisManager"] = _PyEXOAnalysis.EXOAnalysisModule_analysisManager_set
    __swig_getmethods__["analysisManager"] = _PyEXOAnalysis.EXOAnalysisModule_analysisManager_get
    if _newclass:analysisManager = _swig_property(_PyEXOAnalysis.EXOAnalysisModule_analysisManager_get, _PyEXOAnalysis.EXOAnalysisModule_analysisManager_set)
    __swig_setmethods__["errorLogger"] = _PyEXOAnalysis.EXOAnalysisModule_errorLogger_set
    __swig_getmethods__["errorLogger"] = _PyEXOAnalysis.EXOAnalysisModule_errorLogger_get
    if _newclass:errorLogger = _swig_property(_PyEXOAnalysis.EXOAnalysisModule_errorLogger_get, _PyEXOAnalysis.EXOAnalysisModule_errorLogger_set)
    __swig_setmethods__["talktoManager"] = _PyEXOAnalysis.EXOAnalysisModule_talktoManager_set
    __swig_getmethods__["talktoManager"] = _PyEXOAnalysis.EXOAnalysisModule_talktoManager_get
    if _newclass:talktoManager = _swig_property(_PyEXOAnalysis.EXOAnalysisModule_talktoManager_get, _PyEXOAnalysis.EXOAnalysisModule_talktoManager_set)
    __swig_setmethods__["ED"] = _PyEXOAnalysis.EXOAnalysisModule_ED_set
    __swig_getmethods__["ED"] = _PyEXOAnalysis.EXOAnalysisModule_ED_get
    if _newclass:ED = _swig_property(_PyEXOAnalysis.EXOAnalysisModule_ED_get, _PyEXOAnalysis.EXOAnalysisModule_ED_set)
    __swig_setmethods__["channelMap"] = _PyEXOAnalysis.EXOAnalysisModule_channelMap_set
    __swig_getmethods__["channelMap"] = _PyEXOAnalysis.EXOAnalysisModule_channelMap_get
    if _newclass:channelMap = _swig_property(_PyEXOAnalysis.EXOAnalysisModule_channelMap_get, _PyEXOAnalysis.EXOAnalysisModule_channelMap_set)
    __swig_setmethods__["input_module"] = _PyEXOAnalysis.EXOAnalysisModule_input_module_set
    __swig_getmethods__["input_module"] = _PyEXOAnalysis.EXOAnalysisModule_input_module_get
    if _newclass:input_module = _swig_property(_PyEXOAnalysis.EXOAnalysisModule_input_module_get, _PyEXOAnalysis.EXOAnalysisModule_input_module_set)
    def __init__(self, *args): 
        if self.__class__ == EXOAnalysisModule:
            _self = None
        else:
            _self = self
        this = _PyEXOAnalysis.new_EXOAnalysisModule(_self, *args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PyEXOAnalysis.delete_EXOAnalysisModule
    __del__ = lambda self : None;
    def Initialize(self): return _PyEXOAnalysis.EXOAnalysisModule_Initialize(self)
    def BeginOfRun(self): return _PyEXOAnalysis.EXOAnalysisModule_BeginOfRun(self)
    def BeginOfEvent(self): return _PyEXOAnalysis.EXOAnalysisModule_BeginOfEvent(self)
    def EndOfEvent(self): return _PyEXOAnalysis.EXOAnalysisModule_EndOfEvent(self)
    def EndOfRun(self): return _PyEXOAnalysis.EXOAnalysisModule_EndOfRun(self)
    def BeginOfRunSegment(self): return _PyEXOAnalysis.EXOAnalysisModule_BeginOfRunSegment(self)
    def EndOfRunSegment(self): return _PyEXOAnalysis.EXOAnalysisModule_EndOfRunSegment(self)
    def TalkTo(self): return _PyEXOAnalysis.EXOAnalysisModule_TalkTo(self)
    def ShutDown(self): return _PyEXOAnalysis.EXOAnalysisModule_ShutDown(self)
    def is_input_module(self): return _PyEXOAnalysis.EXOAnalysisModule_is_input_module(self)
    def get_name(self): return _PyEXOAnalysis.EXOAnalysisModule_get_name(self)
    def __disown__(self):
        self.this.disown()
        _PyEXOAnalysis.disown_EXOAnalysisModule(self)
        return weakref_proxy(self)
EXOAnalysisModule_swigregister = _PyEXOAnalysis.EXOAnalysisModule_swigregister
EXOAnalysisModule_swigregister(EXOAnalysisModule)

class EXOInputModule(EXOAnalysisModule):
    __swig_setmethods__ = {}
    for _s in [EXOAnalysisModule]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, EXOInputModule, name, value)
    __swig_getmethods__ = {}
    for _s in [EXOAnalysisModule]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, EXOInputModule, name)
    __repr__ = _swig_repr
    __swig_setmethods__["filename"] = _PyEXOAnalysis.EXOInputModule_filename_set
    __swig_getmethods__["filename"] = _PyEXOAnalysis.EXOInputModule_filename_get
    if _newclass:filename = _swig_property(_PyEXOAnalysis.EXOInputModule_filename_get, _PyEXOAnalysis.EXOInputModule_filename_set)
    __swig_setmethods__["last_filename"] = _PyEXOAnalysis.EXOInputModule_last_filename_set
    __swig_getmethods__["last_filename"] = _PyEXOAnalysis.EXOInputModule_last_filename_get
    if _newclass:last_filename = _swig_property(_PyEXOAnalysis.EXOInputModule_last_filename_get, _PyEXOAnalysis.EXOInputModule_last_filename_set)
    def __init__(self, *args): 
        if self.__class__ == EXOInputModule:
            _self = None
        else:
            _self = self
        this = _PyEXOAnalysis.new_EXOInputModule(_self, *args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PyEXOAnalysis.delete_EXOInputModule
    __del__ = lambda self : None;
    def continue_analysis(self): return _PyEXOAnalysis.EXOInputModule_continue_analysis(self)
    def get_run_number(self): return _PyEXOAnalysis.EXOInputModule_get_run_number(self)
    def get_event_number(self): return _PyEXOAnalysis.EXOInputModule_get_event_number(self)
    def file_type_recognized(self): return _PyEXOAnalysis.EXOInputModule_file_type_recognized(self)
    def is_new_run_segment(self): return _PyEXOAnalysis.EXOInputModule_is_new_run_segment(self)
    def __disown__(self):
        self.this.disown()
        _PyEXOAnalysis.disown_EXOInputModule(self)
        return weakref_proxy(self)
EXOInputModule_swigregister = _PyEXOAnalysis.EXOInputModule_swigregister
EXOInputModule_swigregister(EXOInputModule)

EXOChannelMap_h = _PyEXOAnalysis.EXOChannelMap_h
class EXOChannelMap(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, EXOChannelMap, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, EXOChannelMap, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _PyEXOAnalysis.new_EXOChannelMap()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PyEXOAnalysis.delete_EXOChannelMap
    __del__ = lambda self : None;
    def Initialize(self, *args): return _PyEXOAnalysis.EXOChannelMap_Initialize(self, *args)
    def get_physical_channel(self, *args): return _PyEXOAnalysis.EXOChannelMap_get_physical_channel(self, *args)
    def get_card_and_channel(self, *args): return _PyEXOAnalysis.EXOChannelMap_get_card_and_channel(self, *args)
    def get_module_address(self, *args): return _PyEXOAnalysis.EXOChannelMap_get_module_address(self, *args)
    def get_card_number(self, *args): return _PyEXOAnalysis.EXOChannelMap_get_card_number(self, *args)
    def create_map_for_version_0(self): return _PyEXOAnalysis.EXOChannelMap_create_map_for_version_0(self)
    def create_map_for_version_1(self): return _PyEXOAnalysis.EXOChannelMap_create_map_for_version_1(self)
    def print_map(self): return _PyEXOAnalysis.EXOChannelMap_print_map(self)
EXOChannelMap_swigregister = _PyEXOAnalysis.EXOChannelMap_swigregister
EXOChannelMap_swigregister(EXOChannelMap)

MAXERRORLENGTH = _PyEXOAnalysis.MAXERRORLENGTH
MAXERRORS = _PyEXOAnalysis.MAXERRORS
EEOk = _PyEXOAnalysis.EEOk
EEDebug = _PyEXOAnalysis.EEDebug
EENotice = _PyEXOAnalysis.EENotice
EEWarning = _PyEXOAnalysis.EEWarning
EEError = _PyEXOAnalysis.EEError
EECritical = _PyEXOAnalysis.EECritical
EEAlert = _PyEXOAnalysis.EEAlert
EEPanic = _PyEXOAnalysis.EEPanic
class EXOErrorLogger(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, EXOErrorLogger, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, EXOErrorLogger, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _PyEXOAnalysis.new_EXOErrorLogger()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PyEXOAnalysis.delete_EXOErrorLogger
    __del__ = lambda self : None;
    def PrintSummary(self): return _PyEXOAnalysis.EXOErrorLogger_PrintSummary(self)
    def set_print_threshold(self, *args): return _PyEXOAnalysis.EXOErrorLogger_set_print_threshold(self, *args)
    __swig_getmethods__["ErrorLevel"] = lambda x: _PyEXOAnalysis.EXOErrorLogger_ErrorLevel
    if _newclass:ErrorLevel = staticmethod(_PyEXOAnalysis.EXOErrorLogger_ErrorLevel)
    def LogError(self, *args): return _PyEXOAnalysis.EXOErrorLogger_LogError(self, *args)
EXOErrorLogger_swigregister = _PyEXOAnalysis.EXOErrorLogger_swigregister
EXOErrorLogger_swigregister(EXOErrorLogger)

def EXOErrorLogger_ErrorLevel(*args):
  return _PyEXOAnalysis.EXOErrorLogger_ErrorLevel(*args)
EXOErrorLogger_ErrorLevel = _PyEXOAnalysis.EXOErrorLogger_ErrorLevel

MAXNUMCOMMAND = _PyEXOAnalysis.MAXNUMCOMMAND
MAXCOMMANDNAME = _PyEXOAnalysis.MAXCOMMANDNAME
MAXCHARPARAMETER = _PyEXOAnalysis.MAXCHARPARAMETER
MAXNAMES = _PyEXOAnalysis.MAXNAMES
class EXOTalkToManager(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, EXOTalkToManager, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, EXOTalkToManager, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _PyEXOAnalysis.new_EXOTalkToManager(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PyEXOAnalysis.delete_EXOTalkToManager
    __del__ = lambda self : None;
    def CreateGenericCommand(self, *args): return _PyEXOAnalysis.EXOTalkToManager_CreateGenericCommand(self, *args)
    def CreateCommand(self, *args): return _PyEXOAnalysis.EXOTalkToManager_CreateCommand(self, *args)
    def show_commands(self): return _PyEXOAnalysis.EXOTalkToManager_show_commands(self)
    def InterpretCommand(self, *args): return _PyEXOAnalysis.EXOTalkToManager_InterpretCommand(self, *args)
    def InterpretStream(self): return _PyEXOAnalysis.EXOTalkToManager_InterpretStream(self)
    def OpenCommandFile(self): return _PyEXOAnalysis.EXOTalkToManager_OpenCommandFile(self)
    def set_filename(self, *args): return _PyEXOAnalysis.EXOTalkToManager_set_filename(self, *args)
    def set_interactive(self, *args): return _PyEXOAnalysis.EXOTalkToManager_set_interactive(self, *args)
    def parse_list_of_names(self, *args): return _PyEXOAnalysis.EXOTalkToManager_parse_list_of_names(self, *args)
    def SearchForFile(self, *args): return _PyEXOAnalysis.EXOTalkToManager_SearchForFile(self, *args)
    def SearchPathForFile(self, *args): return _PyEXOAnalysis.EXOTalkToManager_SearchPathForFile(self, *args)
    def SplitPath(self, *args): return _PyEXOAnalysis.EXOTalkToManager_SplitPath(self, *args)
EXOTalkToManager_swigregister = _PyEXOAnalysis.EXOTalkToManager_swigregister
EXOTalkToManager_swigregister(EXOTalkToManager)

class EXOCalibManager(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, EXOCalibManager, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, EXOCalibManager, name)
    __repr__ = _swig_repr
    def __init__(self, errorLogger = None): 
        this = _PyEXOAnalysis.new_EXOCalibManager(errorLogger)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PyEXOAnalysis.delete_EXOCalibManager
    __del__ = lambda self : None;
    def registerHandler(self, *args): return _PyEXOAnalysis.EXOCalibManager_registerHandler(self, *args)
    def init(self): return _PyEXOAnalysis.EXOCalibManager_init(self)
    def setMetadataSource(self, *args): return _PyEXOAnalysis.EXOCalibManager_setMetadataSource(self, *args)
    def setTimestampSource(self, *args): return _PyEXOAnalysis.EXOCalibManager_setTimestampSource(self, *args)
    def newEvent(self, *args): return _PyEXOAnalysis.EXOCalibManager_newEvent(self, *args)
    def getCalib(self, *args): return _PyEXOAnalysis.EXOCalibManager_getCalib(self, *args)
EXOCalibManager_swigregister = _PyEXOAnalysis.EXOCalibManager_swigregister
EXOCalibManager_swigregister(EXOCalibManager)

class EXOTreeInputModule(EXOInputModule):
    __swig_setmethods__ = {}
    for _s in [EXOInputModule]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, EXOTreeInputModule, name, value)
    __swig_getmethods__ = {}
    for _s in [EXOInputModule]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, EXOTreeInputModule, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _PyEXOAnalysis.new_EXOTreeInputModule(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PyEXOAnalysis.delete_EXOTreeInputModule
    __del__ = lambda self : None;
    def open_root_file(self): return _PyEXOAnalysis.EXOTreeInputModule_open_root_file(self)
    def close_root_file(self): return _PyEXOAnalysis.EXOTreeInputModule_close_root_file(self)
    def continue_analysis(self): return _PyEXOAnalysis.EXOTreeInputModule_continue_analysis(self)
    def file_type_recognized(self): return _PyEXOAnalysis.EXOTreeInputModule_file_type_recognized(self)
    def Initialize(self): return _PyEXOAnalysis.EXOTreeInputModule_Initialize(self)
    def BeginOfEvent(self): return _PyEXOAnalysis.EXOTreeInputModule_BeginOfEvent(self)
    def EndOfEvent(self): return _PyEXOAnalysis.EXOTreeInputModule_EndOfEvent(self)
    def ShutDown(self): return _PyEXOAnalysis.EXOTreeInputModule_ShutDown(self)
    def get_run_number(self): return _PyEXOAnalysis.EXOTreeInputModule_get_run_number(self)
    def get_event_number(self): return _PyEXOAnalysis.EXOTreeInputModule_get_event_number(self)
EXOTreeInputModule_swigregister = _PyEXOAnalysis.EXOTreeInputModule_swigregister
EXOTreeInputModule_swigregister(EXOTreeInputModule)

class EXOEventData(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, EXOEventData, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, EXOEventData, name)
    __repr__ = _swig_repr
    __swig_setmethods__["header"] = _PyEXOAnalysis.EXOEventData_header_set
    __swig_getmethods__["header"] = _PyEXOAnalysis.EXOEventData_header_get
    if _newclass:header = _swig_property(_PyEXOAnalysis.EXOEventData_header_get, _PyEXOAnalysis.EXOEventData_header_set)
    __swig_setmethods__["nr"] = _PyEXOAnalysis.EXOEventData_nr_set
    __swig_getmethods__["nr"] = _PyEXOAnalysis.EXOEventData_nr_get
    if _newclass:nr = _swig_property(_PyEXOAnalysis.EXOEventData_nr_get, _PyEXOAnalysis.EXOEventData_nr_set)
    __swig_setmethods__["ne"] = _PyEXOAnalysis.EXOEventData_ne_set
    __swig_getmethods__["ne"] = _PyEXOAnalysis.EXOEventData_ne_get
    if _newclass:ne = _swig_property(_PyEXOAnalysis.EXOEventData_ne_get, _PyEXOAnalysis.EXOEventData_ne_set)
    __swig_setmethods__["g4ne"] = _PyEXOAnalysis.EXOEventData_g4ne_set
    __swig_getmethods__["g4ne"] = _PyEXOAnalysis.EXOEventData_g4ne_get
    if _newclass:g4ne = _swig_property(_PyEXOAnalysis.EXOEventData_g4ne_get, _PyEXOAnalysis.EXOEventData_g4ne_set)
    __swig_setmethods__["subne"] = _PyEXOAnalysis.EXOEventData_subne_set
    __swig_getmethods__["subne"] = _PyEXOAnalysis.EXOEventData_subne_get
    if _newclass:subne = _swig_property(_PyEXOAnalysis.EXOEventData_subne_get, _PyEXOAnalysis.EXOEventData_subne_set)
    __swig_setmethods__["mcfid"] = _PyEXOAnalysis.EXOEventData_mcfid_set
    __swig_getmethods__["mcfid"] = _PyEXOAnalysis.EXOEventData_mcfid_get
    if _newclass:mcfid = _swig_property(_PyEXOAnalysis.EXOEventData_mcfid_get, _PyEXOAnalysis.EXOEventData_mcfid_set)
    __swig_setmethods__["svn_rev"] = _PyEXOAnalysis.EXOEventData_svn_rev_set
    __swig_getmethods__["svn_rev"] = _PyEXOAnalysis.EXOEventData_svn_rev_get
    if _newclass:svn_rev = _swig_property(_PyEXOAnalysis.EXOEventData_svn_rev_get, _PyEXOAnalysis.EXOEventData_svn_rev_set)
    __swig_setmethods__["build_id"] = _PyEXOAnalysis.EXOEventData_build_id_set
    __swig_getmethods__["build_id"] = _PyEXOAnalysis.EXOEventData_build_id_get
    if _newclass:build_id = _swig_property(_PyEXOAnalysis.EXOEventData_build_id_get, _PyEXOAnalysis.EXOEventData_build_id_set)
    __swig_setmethods__["compressionid"] = _PyEXOAnalysis.EXOEventData_compressionid_set
    __swig_getmethods__["compressionid"] = _PyEXOAnalysis.EXOEventData_compressionid_get
    if _newclass:compressionid = _swig_property(_PyEXOAnalysis.EXOEventData_compressionid_get, _PyEXOAnalysis.EXOEventData_compressionid_set)
    __swig_setmethods__["frameid"] = _PyEXOAnalysis.EXOEventData_frameid_set
    __swig_getmethods__["frameid"] = _PyEXOAnalysis.EXOEventData_frameid_get
    if _newclass:frameid = _swig_property(_PyEXOAnalysis.EXOEventData_frameid_get, _PyEXOAnalysis.EXOEventData_frameid_set)
    __swig_setmethods__["framerev"] = _PyEXOAnalysis.EXOEventData_framerev_set
    __swig_getmethods__["framerev"] = _PyEXOAnalysis.EXOEventData_framerev_get
    if _newclass:framerev = _swig_property(_PyEXOAnalysis.EXOEventData_framerev_get, _PyEXOAnalysis.EXOEventData_framerev_set)
    __swig_setmethods__["cc"] = _PyEXOAnalysis.EXOEventData_cc_set
    __swig_getmethods__["cc"] = _PyEXOAnalysis.EXOEventData_cc_get
    if _newclass:cc = _swig_property(_PyEXOAnalysis.EXOEventData_cc_get, _PyEXOAnalysis.EXOEventData_cc_set)
    __swig_setmethods__["trigcount"] = _PyEXOAnalysis.EXOEventData_trigcount_set
    __swig_getmethods__["trigcount"] = _PyEXOAnalysis.EXOEventData_trigcount_get
    if _newclass:trigcount = _swig_property(_PyEXOAnalysis.EXOEventData_trigcount_get, _PyEXOAnalysis.EXOEventData_trigcount_set)
    __swig_setmethods__["trigsec"] = _PyEXOAnalysis.EXOEventData_trigsec_set
    __swig_getmethods__["trigsec"] = _PyEXOAnalysis.EXOEventData_trigsec_get
    if _newclass:trigsec = _swig_property(_PyEXOAnalysis.EXOEventData_trigsec_get, _PyEXOAnalysis.EXOEventData_trigsec_set)
    __swig_setmethods__["trigsub"] = _PyEXOAnalysis.EXOEventData_trigsub_set
    __swig_getmethods__["trigsub"] = _PyEXOAnalysis.EXOEventData_trigsub_get
    if _newclass:trigsub = _swig_property(_PyEXOAnalysis.EXOEventData_trigsub_get, _PyEXOAnalysis.EXOEventData_trigsub_set)
    __swig_setmethods__["trigdrift"] = _PyEXOAnalysis.EXOEventData_trigdrift_set
    __swig_getmethods__["trigdrift"] = _PyEXOAnalysis.EXOEventData_trigdrift_get
    if _newclass:trigdrift = _swig_property(_PyEXOAnalysis.EXOEventData_trigdrift_get, _PyEXOAnalysis.EXOEventData_trigdrift_set)
    __swig_setmethods__["sn"] = _PyEXOAnalysis.EXOEventData_sn_set
    __swig_getmethods__["sn"] = _PyEXOAnalysis.EXOEventData_sn_get
    if _newclass:sn = _swig_property(_PyEXOAnalysis.EXOEventData_sn_get, _PyEXOAnalysis.EXOEventData_sn_set)
    __swig_setmethods__["sr"] = _PyEXOAnalysis.EXOEventData_sr_set
    __swig_getmethods__["sr"] = _PyEXOAnalysis.EXOEventData_sr_get
    if _newclass:sr = _swig_property(_PyEXOAnalysis.EXOEventData_sr_get, _PyEXOAnalysis.EXOEventData_sr_set)
    __swig_setmethods__["trigsum"] = _PyEXOAnalysis.EXOEventData_trigsum_set
    __swig_getmethods__["trigsum"] = _PyEXOAnalysis.EXOEventData_trigsum_get
    if _newclass:trigsum = _swig_property(_PyEXOAnalysis.EXOEventData_trigsum_get, _PyEXOAnalysis.EXOEventData_trigsum_set)
    __swig_setmethods__["_in"] = _PyEXOAnalysis.EXOEventData__in_set
    __swig_getmethods__["_in"] = _PyEXOAnalysis.EXOEventData__in_get
    if _newclass:_in = _swig_property(_PyEXOAnalysis.EXOEventData__in_get, _PyEXOAnalysis.EXOEventData__in_set)
    __swig_setmethods__["ir"] = _PyEXOAnalysis.EXOEventData_ir_set
    __swig_getmethods__["ir"] = _PyEXOAnalysis.EXOEventData_ir_get
    if _newclass:ir = _swig_property(_PyEXOAnalysis.EXOEventData_ir_get, _PyEXOAnalysis.EXOEventData_ir_set)
    __swig_setmethods__["indsum"] = _PyEXOAnalysis.EXOEventData_indsum_set
    __swig_getmethods__["indsum"] = _PyEXOAnalysis.EXOEventData_indsum_get
    if _newclass:indsum = _swig_property(_PyEXOAnalysis.EXOEventData_indsum_get, _PyEXOAnalysis.EXOEventData_indsum_set)
    __swig_setmethods__["trigoff"] = _PyEXOAnalysis.EXOEventData_trigoff_set
    __swig_getmethods__["trigoff"] = _PyEXOAnalysis.EXOEventData_trigoff_get
    if _newclass:trigoff = _swig_property(_PyEXOAnalysis.EXOEventData_trigoff_get, _PyEXOAnalysis.EXOEventData_trigoff_set)
    __swig_setmethods__["ebit"] = _PyEXOAnalysis.EXOEventData_ebit_set
    __swig_getmethods__["ebit"] = _PyEXOAnalysis.EXOEventData_ebit_get
    if _newclass:ebit = _swig_property(_PyEXOAnalysis.EXOEventData_ebit_get, _PyEXOAnalysis.EXOEventData_ebit_set)
    __swig_setmethods__["src"] = _PyEXOAnalysis.EXOEventData_src_set
    __swig_getmethods__["src"] = _PyEXOAnalysis.EXOEventData_src_get
    if _newclass:src = _swig_property(_PyEXOAnalysis.EXOEventData_src_get, _PyEXOAnalysis.EXOEventData_src_set)
    __swig_setmethods__["samplecount"] = _PyEXOAnalysis.EXOEventData_samplecount_set
    __swig_getmethods__["samplecount"] = _PyEXOAnalysis.EXOEventData_samplecount_get
    if _newclass:samplecount = _swig_property(_PyEXOAnalysis.EXOEventData_samplecount_get, _PyEXOAnalysis.EXOEventData_samplecount_set)
    __swig_setmethods__["npart"] = _PyEXOAnalysis.EXOEventData_npart_set
    __swig_getmethods__["npart"] = _PyEXOAnalysis.EXOEventData_npart_get
    if _newclass:npart = _swig_property(_PyEXOAnalysis.EXOEventData_npart_get, _PyEXOAnalysis.EXOEventData_npart_set)
    __swig_setmethods__["idpart"] = _PyEXOAnalysis.EXOEventData_idpart_set
    __swig_getmethods__["idpart"] = _PyEXOAnalysis.EXOEventData_idpart_get
    if _newclass:idpart = _swig_property(_PyEXOAnalysis.EXOEventData_idpart_get, _PyEXOAnalysis.EXOEventData_idpart_set)
    __swig_setmethods__["epart"] = _PyEXOAnalysis.EXOEventData_epart_set
    __swig_getmethods__["epart"] = _PyEXOAnalysis.EXOEventData_epart_get
    if _newclass:epart = _swig_property(_PyEXOAnalysis.EXOEventData_epart_get, _PyEXOAnalysis.EXOEventData_epart_set)
    __swig_setmethods__["qpart"] = _PyEXOAnalysis.EXOEventData_qpart_set
    __swig_getmethods__["qpart"] = _PyEXOAnalysis.EXOEventData_qpart_get
    if _newclass:qpart = _swig_property(_PyEXOAnalysis.EXOEventData_qpart_get, _PyEXOAnalysis.EXOEventData_qpart_set)
    __swig_setmethods__["apart"] = _PyEXOAnalysis.EXOEventData_apart_set
    __swig_getmethods__["apart"] = _PyEXOAnalysis.EXOEventData_apart_get
    if _newclass:apart = _swig_property(_PyEXOAnalysis.EXOEventData_apart_get, _PyEXOAnalysis.EXOEventData_apart_set)
    __swig_setmethods__["expart"] = _PyEXOAnalysis.EXOEventData_expart_set
    __swig_getmethods__["expart"] = _PyEXOAnalysis.EXOEventData_expart_get
    if _newclass:expart = _swig_property(_PyEXOAnalysis.EXOEventData_expart_get, _PyEXOAnalysis.EXOEventData_expart_set)
    __swig_setmethods__["qbeta"] = _PyEXOAnalysis.EXOEventData_qbeta_set
    __swig_getmethods__["qbeta"] = _PyEXOAnalysis.EXOEventData_qbeta_get
    if _newclass:qbeta = _swig_property(_PyEXOAnalysis.EXOEventData_qbeta_get, _PyEXOAnalysis.EXOEventData_qbeta_set)
    __swig_setmethods__["x0"] = _PyEXOAnalysis.EXOEventData_x0_set
    __swig_getmethods__["x0"] = _PyEXOAnalysis.EXOEventData_x0_get
    if _newclass:x0 = _swig_property(_PyEXOAnalysis.EXOEventData_x0_get, _PyEXOAnalysis.EXOEventData_x0_set)
    __swig_setmethods__["y0"] = _PyEXOAnalysis.EXOEventData_y0_set
    __swig_getmethods__["y0"] = _PyEXOAnalysis.EXOEventData_y0_get
    if _newclass:y0 = _swig_property(_PyEXOAnalysis.EXOEventData_y0_get, _PyEXOAnalysis.EXOEventData_y0_set)
    __swig_setmethods__["z0"] = _PyEXOAnalysis.EXOEventData_z0_set
    __swig_getmethods__["z0"] = _PyEXOAnalysis.EXOEventData_z0_get
    if _newclass:z0 = _swig_property(_PyEXOAnalysis.EXOEventData_z0_get, _PyEXOAnalysis.EXOEventData_z0_set)
    __swig_setmethods__["nq"] = _PyEXOAnalysis.EXOEventData_nq_set
    __swig_getmethods__["nq"] = _PyEXOAnalysis.EXOEventData_nq_get
    if _newclass:nq = _swig_property(_PyEXOAnalysis.EXOEventData_nq_get, _PyEXOAnalysis.EXOEventData_nq_set)
    __swig_setmethods__["ixq"] = _PyEXOAnalysis.EXOEventData_ixq_set
    __swig_getmethods__["ixq"] = _PyEXOAnalysis.EXOEventData_ixq_get
    if _newclass:ixq = _swig_property(_PyEXOAnalysis.EXOEventData_ixq_get, _PyEXOAnalysis.EXOEventData_ixq_set)
    __swig_setmethods__["iyq"] = _PyEXOAnalysis.EXOEventData_iyq_set
    __swig_getmethods__["iyq"] = _PyEXOAnalysis.EXOEventData_iyq_get
    if _newclass:iyq = _swig_property(_PyEXOAnalysis.EXOEventData_iyq_get, _PyEXOAnalysis.EXOEventData_iyq_set)
    __swig_setmethods__["izq"] = _PyEXOAnalysis.EXOEventData_izq_set
    __swig_getmethods__["izq"] = _PyEXOAnalysis.EXOEventData_izq_get
    if _newclass:izq = _swig_property(_PyEXOAnalysis.EXOEventData_izq_get, _PyEXOAnalysis.EXOEventData_izq_set)
    __swig_setmethods__["etq"] = _PyEXOAnalysis.EXOEventData_etq_set
    __swig_getmethods__["etq"] = _PyEXOAnalysis.EXOEventData_etq_get
    if _newclass:etq = _swig_property(_PyEXOAnalysis.EXOEventData_etq_get, _PyEXOAnalysis.EXOEventData_etq_set)
    __swig_setmethods__["eiq"] = _PyEXOAnalysis.EXOEventData_eiq_set
    __swig_getmethods__["eiq"] = _PyEXOAnalysis.EXOEventData_eiq_get
    if _newclass:eiq = _swig_property(_PyEXOAnalysis.EXOEventData_eiq_get, _PyEXOAnalysis.EXOEventData_eiq_set)
    __swig_setmethods__["napd"] = _PyEXOAnalysis.EXOEventData_napd_set
    __swig_getmethods__["napd"] = _PyEXOAnalysis.EXOEventData_napd_get
    if _newclass:napd = _swig_property(_PyEXOAnalysis.EXOEventData_napd_get, _PyEXOAnalysis.EXOEventData_napd_set)
    __swig_setmethods__["apd_hits"] = _PyEXOAnalysis.EXOEventData_apd_hits_set
    __swig_getmethods__["apd_hits"] = _PyEXOAnalysis.EXOEventData_apd_hits_get
    if _newclass:apd_hits = _swig_property(_PyEXOAnalysis.EXOEventData_apd_hits_get, _PyEXOAnalysis.EXOEventData_apd_hits_set)
    __swig_setmethods__["totalph"] = _PyEXOAnalysis.EXOEventData_totalph_set
    __swig_getmethods__["totalph"] = _PyEXOAnalysis.EXOEventData_totalph_get
    if _newclass:totalph = _swig_property(_PyEXOAnalysis.EXOEventData_totalph_get, _PyEXOAnalysis.EXOEventData_totalph_set)
    __swig_setmethods__["hitsp1"] = _PyEXOAnalysis.EXOEventData_hitsp1_set
    __swig_getmethods__["hitsp1"] = _PyEXOAnalysis.EXOEventData_hitsp1_get
    if _newclass:hitsp1 = _swig_property(_PyEXOAnalysis.EXOEventData_hitsp1_get, _PyEXOAnalysis.EXOEventData_hitsp1_set)
    __swig_setmethods__["hitsp2"] = _PyEXOAnalysis.EXOEventData_hitsp2_set
    __swig_getmethods__["hitsp2"] = _PyEXOAnalysis.EXOEventData_hitsp2_get
    if _newclass:hitsp2 = _swig_property(_PyEXOAnalysis.EXOEventData_hitsp2_get, _PyEXOAnalysis.EXOEventData_hitsp2_set)
    __swig_setmethods__["esalt"] = _PyEXOAnalysis.EXOEventData_esalt_set
    __swig_getmethods__["esalt"] = _PyEXOAnalysis.EXOEventData_esalt_get
    if _newclass:esalt = _swig_property(_PyEXOAnalysis.EXOEventData_esalt_get, _PyEXOAnalysis.EXOEventData_esalt_set)
    __swig_setmethods__["eshield"] = _PyEXOAnalysis.EXOEventData_eshield_set
    __swig_getmethods__["eshield"] = _PyEXOAnalysis.EXOEventData_eshield_get
    if _newclass:eshield = _swig_property(_PyEXOAnalysis.EXOEventData_eshield_get, _PyEXOAnalysis.EXOEventData_eshield_set)
    __swig_setmethods__["eoutcry"] = _PyEXOAnalysis.EXOEventData_eoutcry_set
    __swig_getmethods__["eoutcry"] = _PyEXOAnalysis.EXOEventData_eoutcry_get
    if _newclass:eoutcry = _swig_property(_PyEXOAnalysis.EXOEventData_eoutcry_get, _PyEXOAnalysis.EXOEventData_eoutcry_set)
    __swig_setmethods__["eincry"] = _PyEXOAnalysis.EXOEventData_eincry_set
    __swig_getmethods__["eincry"] = _PyEXOAnalysis.EXOEventData_eincry_get
    if _newclass:eincry = _swig_property(_PyEXOAnalysis.EXOEventData_eincry_get, _PyEXOAnalysis.EXOEventData_eincry_set)
    __swig_setmethods__["ehfe"] = _PyEXOAnalysis.EXOEventData_ehfe_set
    __swig_getmethods__["ehfe"] = _PyEXOAnalysis.EXOEventData_ehfe_get
    if _newclass:ehfe = _swig_property(_PyEXOAnalysis.EXOEventData_ehfe_get, _PyEXOAnalysis.EXOEventData_ehfe_set)
    __swig_setmethods__["evessel"] = _PyEXOAnalysis.EXOEventData_evessel_set
    __swig_getmethods__["evessel"] = _PyEXOAnalysis.EXOEventData_evessel_get
    if _newclass:evessel = _swig_property(_PyEXOAnalysis.EXOEventData_evessel_get, _PyEXOAnalysis.EXOEventData_evessel_set)
    __swig_setmethods__["elxet"] = _PyEXOAnalysis.EXOEventData_elxet_set
    __swig_getmethods__["elxet"] = _PyEXOAnalysis.EXOEventData_elxet_get
    if _newclass:elxet = _swig_property(_PyEXOAnalysis.EXOEventData_elxet_get, _PyEXOAnalysis.EXOEventData_elxet_set)
    __swig_setmethods__["elxei"] = _PyEXOAnalysis.EXOEventData_elxei_set
    __swig_getmethods__["elxei"] = _PyEXOAnalysis.EXOEventData_elxei_get
    if _newclass:elxei = _swig_property(_PyEXOAnalysis.EXOEventData_elxei_get, _PyEXOAnalysis.EXOEventData_elxei_set)
    __swig_setmethods__["ecathode_photons"] = _PyEXOAnalysis.EXOEventData_ecathode_photons_set
    __swig_getmethods__["ecathode_photons"] = _PyEXOAnalysis.EXOEventData_ecathode_photons_get
    if _newclass:ecathode_photons = _swig_property(_PyEXOAnalysis.EXOEventData_ecathode_photons_get, _PyEXOAnalysis.EXOEventData_ecathode_photons_set)
    __swig_setmethods__["eanodes_photons"] = _PyEXOAnalysis.EXOEventData_eanodes_photons_set
    __swig_getmethods__["eanodes_photons"] = _PyEXOAnalysis.EXOEventData_eanodes_photons_get
    if _newclass:eanodes_photons = _swig_property(_PyEXOAnalysis.EXOEventData_eanodes_photons_get, _PyEXOAnalysis.EXOEventData_eanodes_photons_set)
    __swig_setmethods__["ewire_supports_photons"] = _PyEXOAnalysis.EXOEventData_ewire_supports_photons_set
    __swig_getmethods__["ewire_supports_photons"] = _PyEXOAnalysis.EXOEventData_ewire_supports_photons_get
    if _newclass:ewire_supports_photons = _swig_property(_PyEXOAnalysis.EXOEventData_ewire_supports_photons_get, _PyEXOAnalysis.EXOEventData_ewire_supports_photons_set)
    __swig_setmethods__["ecathode_ring_photons"] = _PyEXOAnalysis.EXOEventData_ecathode_ring_photons_set
    __swig_getmethods__["ecathode_ring_photons"] = _PyEXOAnalysis.EXOEventData_ecathode_ring_photons_get
    if _newclass:ecathode_ring_photons = _swig_property(_PyEXOAnalysis.EXOEventData_ecathode_ring_photons_get, _PyEXOAnalysis.EXOEventData_ecathode_ring_photons_set)
    __swig_setmethods__["ereflector_photons"] = _PyEXOAnalysis.EXOEventData_ereflector_photons_set
    __swig_getmethods__["ereflector_photons"] = _PyEXOAnalysis.EXOEventData_ereflector_photons_get
    if _newclass:ereflector_photons = _swig_property(_PyEXOAnalysis.EXOEventData_ereflector_photons_get, _PyEXOAnalysis.EXOEventData_ereflector_photons_set)
    __swig_setmethods__["eapd_frames_photons"] = _PyEXOAnalysis.EXOEventData_eapd_frames_photons_set
    __swig_getmethods__["eapd_frames_photons"] = _PyEXOAnalysis.EXOEventData_eapd_frames_photons_get
    if _newclass:eapd_frames_photons = _swig_property(_PyEXOAnalysis.EXOEventData_eapd_frames_photons_get, _PyEXOAnalysis.EXOEventData_eapd_frames_photons_set)
    __swig_setmethods__["elxe_photons"] = _PyEXOAnalysis.EXOEventData_elxe_photons_set
    __swig_getmethods__["elxe_photons"] = _PyEXOAnalysis.EXOEventData_elxe_photons_get
    if _newclass:elxe_photons = _swig_property(_PyEXOAnalysis.EXOEventData_elxe_photons_get, _PyEXOAnalysis.EXOEventData_elxe_photons_set)
    __swig_setmethods__["evessel_photons"] = _PyEXOAnalysis.EXOEventData_evessel_photons_set
    __swig_getmethods__["evessel_photons"] = _PyEXOAnalysis.EXOEventData_evessel_photons_get
    if _newclass:evessel_photons = _swig_property(_PyEXOAnalysis.EXOEventData_evessel_photons_get, _PyEXOAnalysis.EXOEventData_evessel_photons_set)
    __swig_setmethods__["eremoved_apds_photons"] = _PyEXOAnalysis.EXOEventData_eremoved_apds_photons_set
    __swig_getmethods__["eremoved_apds_photons"] = _PyEXOAnalysis.EXOEventData_eremoved_apds_photons_get
    if _newclass:eremoved_apds_photons = _swig_property(_PyEXOAnalysis.EXOEventData_eremoved_apds_photons_get, _PyEXOAnalysis.EXOEventData_eremoved_apds_photons_set)
    __swig_setmethods__["efield_rings_photons"] = _PyEXOAnalysis.EXOEventData_efield_rings_photons_set
    __swig_getmethods__["efield_rings_photons"] = _PyEXOAnalysis.EXOEventData_efield_rings_photons_get
    if _newclass:efield_rings_photons = _swig_property(_PyEXOAnalysis.EXOEventData_efield_rings_photons_get, _PyEXOAnalysis.EXOEventData_efield_rings_photons_set)
    __swig_setmethods__["ncl"] = _PyEXOAnalysis.EXOEventData_ncl_set
    __swig_getmethods__["ncl"] = _PyEXOAnalysis.EXOEventData_ncl_get
    if _newclass:ncl = _swig_property(_PyEXOAnalysis.EXOEventData_ncl_get, _PyEXOAnalysis.EXOEventData_ncl_set)
    __swig_setmethods__["ercl"] = _PyEXOAnalysis.EXOEventData_ercl_set
    __swig_getmethods__["ercl"] = _PyEXOAnalysis.EXOEventData_ercl_get
    if _newclass:ercl = _swig_property(_PyEXOAnalysis.EXOEventData_ercl_get, _PyEXOAnalysis.EXOEventData_ercl_set)
    __swig_setmethods__["eccl"] = _PyEXOAnalysis.EXOEventData_eccl_set
    __swig_getmethods__["eccl"] = _PyEXOAnalysis.EXOEventData_eccl_get
    if _newclass:eccl = _swig_property(_PyEXOAnalysis.EXOEventData_eccl_get, _PyEXOAnalysis.EXOEventData_eccl_set)
    __swig_setmethods__["eerrcl"] = _PyEXOAnalysis.EXOEventData_eerrcl_set
    __swig_getmethods__["eerrcl"] = _PyEXOAnalysis.EXOEventData_eerrcl_get
    if _newclass:eerrcl = _swig_property(_PyEXOAnalysis.EXOEventData_eerrcl_get, _PyEXOAnalysis.EXOEventData_eerrcl_set)
    __swig_setmethods__["xcl"] = _PyEXOAnalysis.EXOEventData_xcl_set
    __swig_getmethods__["xcl"] = _PyEXOAnalysis.EXOEventData_xcl_get
    if _newclass:xcl = _swig_property(_PyEXOAnalysis.EXOEventData_xcl_get, _PyEXOAnalysis.EXOEventData_xcl_set)
    __swig_setmethods__["ycl"] = _PyEXOAnalysis.EXOEventData_ycl_set
    __swig_getmethods__["ycl"] = _PyEXOAnalysis.EXOEventData_ycl_get
    if _newclass:ycl = _swig_property(_PyEXOAnalysis.EXOEventData_ycl_get, _PyEXOAnalysis.EXOEventData_ycl_set)
    __swig_setmethods__["ucl"] = _PyEXOAnalysis.EXOEventData_ucl_set
    __swig_getmethods__["ucl"] = _PyEXOAnalysis.EXOEventData_ucl_get
    if _newclass:ucl = _swig_property(_PyEXOAnalysis.EXOEventData_ucl_get, _PyEXOAnalysis.EXOEventData_ucl_set)
    __swig_setmethods__["vcl"] = _PyEXOAnalysis.EXOEventData_vcl_set
    __swig_getmethods__["vcl"] = _PyEXOAnalysis.EXOEventData_vcl_get
    if _newclass:vcl = _swig_property(_PyEXOAnalysis.EXOEventData_vcl_get, _PyEXOAnalysis.EXOEventData_vcl_set)
    __swig_setmethods__["zcl"] = _PyEXOAnalysis.EXOEventData_zcl_set
    __swig_getmethods__["zcl"] = _PyEXOAnalysis.EXOEventData_zcl_get
    if _newclass:zcl = _swig_property(_PyEXOAnalysis.EXOEventData_zcl_get, _PyEXOAnalysis.EXOEventData_zcl_set)
    __swig_setmethods__["tcl"] = _PyEXOAnalysis.EXOEventData_tcl_set
    __swig_getmethods__["tcl"] = _PyEXOAnalysis.EXOEventData_tcl_get
    if _newclass:tcl = _swig_property(_PyEXOAnalysis.EXOEventData_tcl_get, _PyEXOAnalysis.EXOEventData_tcl_set)
    __swig_setmethods__["ncscl"] = _PyEXOAnalysis.EXOEventData_ncscl_set
    __swig_getmethods__["ncscl"] = _PyEXOAnalysis.EXOEventData_ncscl_get
    if _newclass:ncscl = _swig_property(_PyEXOAnalysis.EXOEventData_ncscl_get, _PyEXOAnalysis.EXOEventData_ncscl_set)
    __swig_setmethods__["iu1cl"] = _PyEXOAnalysis.EXOEventData_iu1cl_set
    __swig_getmethods__["iu1cl"] = _PyEXOAnalysis.EXOEventData_iu1cl_get
    if _newclass:iu1cl = _swig_property(_PyEXOAnalysis.EXOEventData_iu1cl_get, _PyEXOAnalysis.EXOEventData_iu1cl_set)
    __swig_setmethods__["iu2cl"] = _PyEXOAnalysis.EXOEventData_iu2cl_set
    __swig_getmethods__["iu2cl"] = _PyEXOAnalysis.EXOEventData_iu2cl_get
    if _newclass:iu2cl = _swig_property(_PyEXOAnalysis.EXOEventData_iu2cl_get, _PyEXOAnalysis.EXOEventData_iu2cl_set)
    __swig_setmethods__["iu3cl"] = _PyEXOAnalysis.EXOEventData_iu3cl_set
    __swig_getmethods__["iu3cl"] = _PyEXOAnalysis.EXOEventData_iu3cl_get
    if _newclass:iu3cl = _swig_property(_PyEXOAnalysis.EXOEventData_iu3cl_get, _PyEXOAnalysis.EXOEventData_iu3cl_set)
    __swig_setmethods__["iu4cl"] = _PyEXOAnalysis.EXOEventData_iu4cl_set
    __swig_getmethods__["iu4cl"] = _PyEXOAnalysis.EXOEventData_iu4cl_get
    if _newclass:iu4cl = _swig_property(_PyEXOAnalysis.EXOEventData_iu4cl_get, _PyEXOAnalysis.EXOEventData_iu4cl_set)
    __swig_setmethods__["nvchcl"] = _PyEXOAnalysis.EXOEventData_nvchcl_set
    __swig_getmethods__["nvchcl"] = _PyEXOAnalysis.EXOEventData_nvchcl_get
    if _newclass:nvchcl = _swig_property(_PyEXOAnalysis.EXOEventData_nvchcl_get, _PyEXOAnalysis.EXOEventData_nvchcl_set)
    __swig_setmethods__["iv1cl"] = _PyEXOAnalysis.EXOEventData_iv1cl_set
    __swig_getmethods__["iv1cl"] = _PyEXOAnalysis.EXOEventData_iv1cl_get
    if _newclass:iv1cl = _swig_property(_PyEXOAnalysis.EXOEventData_iv1cl_get, _PyEXOAnalysis.EXOEventData_iv1cl_set)
    __swig_setmethods__["iv2cl"] = _PyEXOAnalysis.EXOEventData_iv2cl_set
    __swig_getmethods__["iv2cl"] = _PyEXOAnalysis.EXOEventData_iv2cl_get
    if _newclass:iv2cl = _swig_property(_PyEXOAnalysis.EXOEventData_iv2cl_get, _PyEXOAnalysis.EXOEventData_iv2cl_set)
    __swig_setmethods__["dhalfcl"] = _PyEXOAnalysis.EXOEventData_dhalfcl_set
    __swig_getmethods__["dhalfcl"] = _PyEXOAnalysis.EXOEventData_dhalfcl_get
    if _newclass:dhalfcl = _swig_property(_PyEXOAnalysis.EXOEventData_dhalfcl_get, _PyEXOAnalysis.EXOEventData_dhalfcl_set)
    __swig_setmethods__["evcl"] = _PyEXOAnalysis.EXOEventData_evcl_set
    __swig_getmethods__["evcl"] = _PyEXOAnalysis.EXOEventData_evcl_get
    if _newclass:evcl = _swig_property(_PyEXOAnalysis.EXOEventData_evcl_get, _PyEXOAnalysis.EXOEventData_evcl_set)
    __swig_setmethods__["ghcl"] = _PyEXOAnalysis.EXOEventData_ghcl_set
    __swig_getmethods__["ghcl"] = _PyEXOAnalysis.EXOEventData_ghcl_get
    if _newclass:ghcl = _swig_property(_PyEXOAnalysis.EXOEventData_ghcl_get, _PyEXOAnalysis.EXOEventData_ghcl_set)
    __swig_setmethods__["tdcl"] = _PyEXOAnalysis.EXOEventData_tdcl_set
    __swig_getmethods__["tdcl"] = _PyEXOAnalysis.EXOEventData_tdcl_get
    if _newclass:tdcl = _swig_property(_PyEXOAnalysis.EXOEventData_tdcl_get, _PyEXOAnalysis.EXOEventData_tdcl_set)
    __swig_setmethods__["fidcl"] = _PyEXOAnalysis.EXOEventData_fidcl_set
    __swig_getmethods__["fidcl"] = _PyEXOAnalysis.EXOEventData_fidcl_get
    if _newclass:fidcl = _swig_property(_PyEXOAnalysis.EXOEventData_fidcl_get, _PyEXOAnalysis.EXOEventData_fidcl_set)
    __swig_setmethods__["nsc"] = _PyEXOAnalysis.EXOEventData_nsc_set
    __swig_getmethods__["nsc"] = _PyEXOAnalysis.EXOEventData_nsc_get
    if _newclass:nsc = _swig_property(_PyEXOAnalysis.EXOEventData_nsc_get, _PyEXOAnalysis.EXOEventData_nsc_set)
    __swig_setmethods__["c1sc"] = _PyEXOAnalysis.EXOEventData_c1sc_set
    __swig_getmethods__["c1sc"] = _PyEXOAnalysis.EXOEventData_c1sc_get
    if _newclass:c1sc = _swig_property(_PyEXOAnalysis.EXOEventData_c1sc_get, _PyEXOAnalysis.EXOEventData_c1sc_set)
    __swig_setmethods__["c1errsc"] = _PyEXOAnalysis.EXOEventData_c1errsc_set
    __swig_getmethods__["c1errsc"] = _PyEXOAnalysis.EXOEventData_c1errsc_get
    if _newclass:c1errsc = _swig_property(_PyEXOAnalysis.EXOEventData_c1errsc_get, _PyEXOAnalysis.EXOEventData_c1errsc_set)
    __swig_setmethods__["c2sc"] = _PyEXOAnalysis.EXOEventData_c2sc_set
    __swig_getmethods__["c2sc"] = _PyEXOAnalysis.EXOEventData_c2sc_get
    if _newclass:c2sc = _swig_property(_PyEXOAnalysis.EXOEventData_c2sc_get, _PyEXOAnalysis.EXOEventData_c2sc_set)
    __swig_setmethods__["c2errsc"] = _PyEXOAnalysis.EXOEventData_c2errsc_set
    __swig_getmethods__["c2errsc"] = _PyEXOAnalysis.EXOEventData_c2errsc_get
    if _newclass:c2errsc = _swig_property(_PyEXOAnalysis.EXOEventData_c2errsc_get, _PyEXOAnalysis.EXOEventData_c2errsc_set)
    __swig_setmethods__["nphe"] = _PyEXOAnalysis.EXOEventData_nphe_set
    __swig_getmethods__["nphe"] = _PyEXOAnalysis.EXOEventData_nphe_get
    if _newclass:nphe = _swig_property(_PyEXOAnalysis.EXOEventData_nphe_get, _PyEXOAnalysis.EXOEventData_nphe_set)
    __swig_setmethods__["csc"] = _PyEXOAnalysis.EXOEventData_csc_set
    __swig_getmethods__["csc"] = _PyEXOAnalysis.EXOEventData_csc_get
    if _newclass:csc = _swig_property(_PyEXOAnalysis.EXOEventData_csc_get, _PyEXOAnalysis.EXOEventData_csc_set)
    __swig_setmethods__["cerrsc"] = _PyEXOAnalysis.EXOEventData_cerrsc_set
    __swig_getmethods__["cerrsc"] = _PyEXOAnalysis.EXOEventData_cerrsc_get
    if _newclass:cerrsc = _swig_property(_PyEXOAnalysis.EXOEventData_cerrsc_get, _PyEXOAnalysis.EXOEventData_cerrsc_set)
    __swig_setmethods__["esc"] = _PyEXOAnalysis.EXOEventData_esc_set
    __swig_getmethods__["esc"] = _PyEXOAnalysis.EXOEventData_esc_get
    if _newclass:esc = _swig_property(_PyEXOAnalysis.EXOEventData_esc_get, _PyEXOAnalysis.EXOEventData_esc_set)
    __swig_setmethods__["tsc"] = _PyEXOAnalysis.EXOEventData_tsc_set
    __swig_getmethods__["tsc"] = _PyEXOAnalysis.EXOEventData_tsc_get
    if _newclass:tsc = _swig_property(_PyEXOAnalysis.EXOEventData_tsc_get, _PyEXOAnalysis.EXOEventData_tsc_set)
    __swig_setmethods__["zsc"] = _PyEXOAnalysis.EXOEventData_zsc_set
    __swig_getmethods__["zsc"] = _PyEXOAnalysis.EXOEventData_zsc_get
    if _newclass:zsc = _swig_property(_PyEXOAnalysis.EXOEventData_zsc_get, _PyEXOAnalysis.EXOEventData_zsc_set)
    __swig_setmethods__["algsc"] = _PyEXOAnalysis.EXOEventData_algsc_set
    __swig_getmethods__["algsc"] = _PyEXOAnalysis.EXOEventData_algsc_get
    if _newclass:algsc = _swig_property(_PyEXOAnalysis.EXOEventData_algsc_get, _PyEXOAnalysis.EXOEventData_algsc_set)
    __swig_setmethods__["fidev"] = _PyEXOAnalysis.EXOEventData_fidev_set
    __swig_getmethods__["fidev"] = _PyEXOAnalysis.EXOEventData_fidev_get
    if _newclass:fidev = _swig_property(_PyEXOAnalysis.EXOEventData_fidev_get, _PyEXOAnalysis.EXOEventData_fidev_set)
    __swig_setmethods__["nsite"] = _PyEXOAnalysis.EXOEventData_nsite_set
    __swig_getmethods__["nsite"] = _PyEXOAnalysis.EXOEventData_nsite_get
    if _newclass:nsite = _swig_property(_PyEXOAnalysis.EXOEventData_nsite_get, _PyEXOAnalysis.EXOEventData_nsite_set)
    __swig_setmethods__["bb0n"] = _PyEXOAnalysis.EXOEventData_bb0n_set
    __swig_getmethods__["bb0n"] = _PyEXOAnalysis.EXOEventData_bb0n_get
    if _newclass:bb0n = _swig_property(_PyEXOAnalysis.EXOEventData_bb0n_get, _PyEXOAnalysis.EXOEventData_bb0n_set)
    __swig_setmethods__["bb2n"] = _PyEXOAnalysis.EXOEventData_bb2n_set
    __swig_getmethods__["bb2n"] = _PyEXOAnalysis.EXOEventData_bb2n_get
    if _newclass:bb2n = _swig_property(_PyEXOAnalysis.EXOEventData_bb2n_get, _PyEXOAnalysis.EXOEventData_bb2n_set)
    __swig_setmethods__["errec"] = _PyEXOAnalysis.EXOEventData_errec_set
    __swig_getmethods__["errec"] = _PyEXOAnalysis.EXOEventData_errec_get
    if _newclass:errec = _swig_property(_PyEXOAnalysis.EXOEventData_errec_get, _PyEXOAnalysis.EXOEventData_errec_set)
    __swig_setmethods__["ecrec"] = _PyEXOAnalysis.EXOEventData_ecrec_set
    __swig_getmethods__["ecrec"] = _PyEXOAnalysis.EXOEventData_ecrec_get
    if _newclass:ecrec = _swig_property(_PyEXOAnalysis.EXOEventData_ecrec_get, _PyEXOAnalysis.EXOEventData_ecrec_set)
    __swig_setmethods__["alpha"] = _PyEXOAnalysis.EXOEventData_alpha_set
    __swig_getmethods__["alpha"] = _PyEXOAnalysis.EXOEventData_alpha_get
    if _newclass:alpha = _swig_property(_PyEXOAnalysis.EXOEventData_alpha_get, _PyEXOAnalysis.EXOEventData_alpha_set)
    __swig_setmethods__["depth"] = _PyEXOAnalysis.EXOEventData_depth_set
    __swig_getmethods__["depth"] = _PyEXOAnalysis.EXOEventData_depth_get
    if _newclass:depth = _swig_property(_PyEXOAnalysis.EXOEventData_depth_get, _PyEXOAnalysis.EXOEventData_depth_set)
    __swig_setmethods__["ecsum"] = _PyEXOAnalysis.EXOEventData_ecsum_set
    __swig_getmethods__["ecsum"] = _PyEXOAnalysis.EXOEventData_ecsum_get
    if _newclass:ecsum = _swig_property(_PyEXOAnalysis.EXOEventData_ecsum_get, _PyEXOAnalysis.EXOEventData_ecsum_set)
    __swig_setmethods__["nsig"] = _PyEXOAnalysis.EXOEventData_nsig_set
    __swig_getmethods__["nsig"] = _PyEXOAnalysis.EXOEventData_nsig_get
    if _newclass:nsig = _swig_property(_PyEXOAnalysis.EXOEventData_nsig_get, _PyEXOAnalysis.EXOEventData_nsig_set)
    __swig_setmethods__["chan"] = _PyEXOAnalysis.EXOEventData_chan_set
    __swig_getmethods__["chan"] = _PyEXOAnalysis.EXOEventData_chan_get
    if _newclass:chan = _swig_property(_PyEXOAnalysis.EXOEventData_chan_get, _PyEXOAnalysis.EXOEventData_chan_set)
    __swig_setmethods__["nsample"] = _PyEXOAnalysis.EXOEventData_nsample_set
    __swig_getmethods__["nsample"] = _PyEXOAnalysis.EXOEventData_nsample_get
    if _newclass:nsample = _swig_property(_PyEXOAnalysis.EXOEventData_nsample_get, _PyEXOAnalysis.EXOEventData_nsample_set)
    __swig_setmethods__["nele"] = _PyEXOAnalysis.EXOEventData_nele_set
    __swig_getmethods__["nele"] = _PyEXOAnalysis.EXOEventData_nele_get
    if _newclass:nele = _swig_property(_PyEXOAnalysis.EXOEventData_nele_get, _PyEXOAnalysis.EXOEventData_nele_set)
    __swig_setmethods__["data"] = _PyEXOAnalysis.EXOEventData_data_set
    __swig_getmethods__["data"] = _PyEXOAnalysis.EXOEventData_data_get
    if _newclass:data = _swig_property(_PyEXOAnalysis.EXOEventData_data_get, _PyEXOAnalysis.EXOEventData_data_set)
    __swig_setmethods__["nqele"] = _PyEXOAnalysis.EXOEventData_nqele_set
    __swig_getmethods__["nqele"] = _PyEXOAnalysis.EXOEventData_nqele_get
    if _newclass:nqele = _swig_property(_PyEXOAnalysis.EXOEventData_nqele_get, _PyEXOAnalysis.EXOEventData_nqele_set)
    __swig_setmethods__["qdata"] = _PyEXOAnalysis.EXOEventData_qdata_set
    __swig_getmethods__["qdata"] = _PyEXOAnalysis.EXOEventData_qdata_get
    if _newclass:qdata = _swig_property(_PyEXOAnalysis.EXOEventData_qdata_get, _PyEXOAnalysis.EXOEventData_qdata_set)
    def __init__(self): 
        this = _PyEXOAnalysis.new_EXOEventData()
        try: self.this.append(this)
        except: self.this = this
    def clear(self): return _PyEXOAnalysis.EXOEventData_clear(self)
    def get_data_as_ndarray(self): return _PyEXOAnalysis.EXOEventData_get_data_as_ndarray(self)
    def get_chan_array_as_ndarray(self): return _PyEXOAnalysis.EXOEventData_get_chan_array_as_ndarray(self)
    __swig_destroy__ = _PyEXOAnalysis.delete_EXOEventData
    __del__ = lambda self : None;
EXOEventData_swigregister = _PyEXOAnalysis.EXOEventData_swigregister
EXOEventData_swigregister(EXOEventData)



